<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>ML and DL</b></center>

<center><b><h1>Lab - 6</b></center>    
<pre>    

# Decision Tree Classifier

In [3]:
from sklearn.datasets import load_iris 

# Import iris data ser using sklearn

In [43]:
data = load_iris()

In [45]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

# Importing the libraries

In [53]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Divide the data into input and output

In [50]:
x = data['data']
y = data['target']

# Splitting the dataset into the Training set and Test set

In [41]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)
print("Training Shape: " , x_train.shape)
print("Testing Shape:  " , x_test.shape)

Training Shape:  (120, 4)
Testing Shape:   (30, 4)


# Fitting DecisionTreeClassifier   on dataset

In [55]:
model = DecisionTreeClassifier(splitter='random')

In [57]:
model.fit(x_train,y_train)

DecisionTreeClassifier(splitter='random')

DecisionTreeClassifier(splitter='random')

# Display Decision Tree

In [59]:
from sklearn import tree
%matplotlib qt

In [61]:
tree.plot_tree(model)

[Text(0.3382352941176471, 0.9375, 'x[2] <= 3.449\ngini = 0.667\nsamples = 120\nvalue = [40, 41, 39]'),
 Text(0.11764705882352941, 0.8125, 'x[2] <= 2.801\ngini = 0.13\nsamples = 43\nvalue = [40, 3, 0]'),
 Text(0.22794117647058826, 0.875, 'True  '),
 Text(0.058823529411764705, 0.6875, 'gini = 0.0\nsamples = 40\nvalue = [40, 0, 0]'),
 Text(0.17647058823529413, 0.6875, 'gini = 0.0\nsamples = 3\nvalue = [0, 3, 0]'),
 Text(0.5588235294117647, 0.8125, 'x[3] <= 1.691\ngini = 0.5\nsamples = 77\nvalue = [0.0, 38.0, 39.0]'),
 Text(0.4485294117647059, 0.875, '  False'),
 Text(0.29411764705882354, 0.6875, 'x[2] <= 4.894\ngini = 0.18\nsamples = 40\nvalue = [0, 36, 4]'),
 Text(0.23529411764705882, 0.5625, 'gini = 0.0\nsamples = 33\nvalue = [0, 33, 0]'),
 Text(0.35294117647058826, 0.5625, 'x[3] <= 1.488\ngini = 0.49\nsamples = 7\nvalue = [0, 3, 4]'),
 Text(0.29411764705882354, 0.4375, 'gini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.4117647058823529, 0.4375, 'x[2] <= 5.673\ngini = 0.5\nsamples =

# Predict the x_test 

In [72]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [68]:
model.score(x_train,y_train)

1.0

In [65]:
model.score(x_test,y_test)

1.0

In [74]:
cm = metrics.confusion_matrix(y_true, y_pred)
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


NameError: name 'ConfusionMatrixDisplay' is not defined

# Import diabetes.csv dataset 

In [85]:
df = pd.read_csv('diabetes.csv')

In [87]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age       Outcome  
0                       0.627   50      Diabetic  
1                       0.351   31  Non Diabetic  
2                       0.672   32      Diabetic  
3                       0.167   21  Non Diabetic  
4                       2.288   33      Diabetic  
..                        ...  ...           ...  
763                     0.171   63  Non Diabetic  
764                     0.340   27  Non Diabetic  
765                     0.245   30  Non Diabetic  
766                     0.349   47      Diabetic  
767                     0.315   23  Non Diabetic  

[768 rows x 9 columns]

# Check the distribution of the target

In [89]:
df['Outcome'].value_counts()

Outcome
Non Diabetic    500
Diabetic        268
Name: count, dtype: int64

# Replace zeros with NaN for specific columns

In [95]:
col = ['Glucose','BloodPressure','BMI','SkinThickness','Insulin']

In [97]:
df[col] = df[col].replace(0, np.nan)

# Check for missing values

In [99]:
df.isnull().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

# Fill missing values with median

In [101]:
 for col in col:
     df[col] = df[col].transform(lambda x : x.fillna(x.median()))

In [103]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

# Visualize Distributions

In [111]:
sns.pairplot(df)

# Convert Targer data into interger code

In [107]:
def convert_target(x):
    if x == 'Diabetic':
        return 1
    else:
        return 0

df['Outcome'] = df['Outcome'].apply(convert_target)

In [109]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0    125.0  33.6   
1              1     85.0           66.0           29.0    125.0  26.6   
2              8    183.0           64.0           29.0    125.0  23.3   
3              1     89.0           66.0           23.0     94.0  28.1   
4              0    137.0           40.0           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0           76.0           48.0    180.0  32.9   
764            2    122.0           70.0           27.0    125.0  36.8   
765            5    121.0           72.0           23.0    112.0  26.2   
766            1    126.0           60.0           29.0    125.0  30.1   
767            1     93.0           70.0           31.0    125.0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

# Divide the data into input and output

In [119]:
x = df.drop(['Outcome'], axis=1)
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0    125.0  33.6   
1              1     85.0           66.0           29.0    125.0  26.6   
2              8    183.0           64.0           29.0    125.0  23.3   
3              1     89.0           66.0           23.0     94.0  28.1   
4              0    137.0           40.0           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10    101.0           76.0           48.0    180.0  32.9   
764            2    122.0           70.0           27.0    125.0  36.8   
765            5    121.0           72.0           23.0    112.0  26.2   
766            1    126.0           60.0           29.0    125.0  30.1   
767            1     93.0           70.0           31.0    125.0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [117]:
y = df['Outcome']

# Splitting the dataset into the Training set and Test set

In [121]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)
print("Training Shape: " , x_train.shape)
print("Testing Shape:  " , x_test.shape)

Training Shape:  (614, 8)
Testing Shape:   (154, 8)


# Create Model

# Fitting DecisionTreeClassifier   on dataset

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

# Display Decision Tree

# Predict the x_test 

# Display Training Accuracy

# Display Test Accuracy

# Confusion Matrix

# Save Model State

In [77]:
import pickle

In [79]:
with open('iris_model.pkl', 'wb') as file:
    pickle.dump(model, file)

# Load Model from Disk

In [81]:
with open('iris_model.pkl', 'rb') as file:
    load_model = pickle.load(file)

In [83]:
load_model.predict(x_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

NameError: name 'y_test' is not defined